/* 
 * Main for simulation
 *
 * Generated by Cares generator, written with Acceleo
 * Author: jpb
 */

package cares.run;

import cares.framework.JsonSeries;
import cares.framework.LogComponent;
import cares.factory.DroneSystem;
import cares.scenario.ScenarLog;
import cares.observation.myDronePositionLogObservationComponent;
// Start of user code  : Additional imports for testDrone
// End of user code

public class MainDroneSystem {

	public static void main(String[] args) {
		DroneSystem root = new DroneSystem();
		// configuration des switches et autres actions
		root.get_InstDrone().setSpeed( 2.0);
		for(int i = 0; i < 2; i++){
        	// configuration des switches et autres actions
            root.get_InstDrone().setDirection( "(1,0,1");
			root.initialize();
			//observations
			ScenarLog simulatedScenario = new ScenarLog(root);
	   		myDronePositionLogObservationComponent DronePositionLogObservationComponent = new myDronePositionLogObservationComponent(  "DronePosition" + i, 1.0);
			DronePositionLogObservationComponent.setDrone( root.get_InstDrone().getAppli());
       	 	simulatedScenario.getCsvLogs().add( DronePositionLogObservationComponent);
        
        
			simulatedScenario.setTime(0,100000);
			simulatedScenario.startSimulation();
			root.end();
        	simulatedScenario.end();
        }
// Start of user code  : Additional code main for testDrone
// End of user code
	}
}
