/* 
 * Scenario implementation
 *
 * Generated by Cares generator, written with Acceleo
 * Author: jpb
 */

package cares.scenario;

import cares.framework.*;
import cares.factory.*;

public class ScenarLog extends Scenario{

	protected DroneSystem application;
	
	public ScenarLog(RootComponent root) {
		super(root);
		application = (DroneSystem) root;
	}
	
	public void eventSimulation() {		 
		if (Clock.getCurrentMS()==25000) {
			application.get_InstDrone().setDirection( "(1,0,-1)"); 
		}
		if (Clock.getCurrentMS()==90000) {
			application.get_InstDrone().setSpeed( 0.5); 
		}
	}
}
