/*
 * myTrajectoryDepthLogObservationComponent
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */
package cares.framework;
import java.io.File;
import java.io.IOException;

import com.fasterxml.jackson.core.JsonFactory;
import com.fasterxml.jackson.core.JsonParser;

public class JsnParser {
	protected JsonParser jsonParser = null;

	public JsnParser() {
	}
	
	public JsonParser getParser(String filename) {
		String path = filePath( filename);
		try {
			jsonParser = new JsonFactory().createParser(new File( path));
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			jsonParser = null;
		}
		return jsonParser;
		}
	public String filePath( String filename ) {
		try {
			String path = new java.io.File(".").getCanonicalPath();
			if (OS.isWindows()) {
				path = path + "\\data\\results\\";//"\\data\\hdf5\\"      
		      } else if (OS.isLinux()) {
		      	 //cmd = properties.getProperty("gdalPath") + "/" + command;
					path = path + "/data/results/";//"\\data\\hdf5\\"
		      } else {
		          System.out.println("OS not supported");
		      }
			return path + filename + ".json";
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			return "";
		}
		
	}
    
}