/*
 * Manager.cpp
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */

#include "Manager.h"
#include "compManager.h"
// Start of user code  : Additional imports for Manager
// End of user code


Manager::Manager(compManager *container)	{
		myContainer = container;
// Start of user code  : Implementation of constructor method

// End of user code
	}
Manager::~Manager(){
// Start of user code  : Implementation of destructor method

// End of user code
	}
void Manager::initialize() {
// Start of user code  : Implementation of initialize method

// End of user code
	}

void Manager::end() {
// Start of user code  : Implementation of end method

// End of user code
	}

void Manager::doStep(int nStep) {
// Start of user code  : Implementation of doStep method
		// to implement
// End of user code
	}
	
	
// Start of user code  : Additional methods

// End of user code
	

void Manager::setDrLocation(Vector3 arg) {
		drLocation = arg;
	}

Vector3 Manager::getNewLocation() {
		return newLocation;
	}
	// +++++++++++++ Access for direction parameter +++++++++++++
Vector3 Manager::getDirection() {
		return direction;
	}
	
void Manager::setDirection(Vector3 arg) {
		direction = arg;
	}

