/*
 * Drone.cpp
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */

#include "compDrone.h"
#include "Drone.h"
compDrone::compDrone(double aFrequency) : LeafComponent( aFrequency) {
		appli = new Drone( this);
		delay = 0;
		delayMax = 0;
		newValue = false;
		isActive = true;
		oldLocation = appli->getLocation();
		newLocation = appli->getLocation();
	}
compDrone::~compDrone()	{}

void compDrone::doOneStep() {
		if (newValue) {
			delay++;
			if (delay == delayMax) {
					oldLocation = newLocation;
					newValue = false;
			}
		}
	}

void compDrone::doStep(int nStep) {	
		if (newValue) {
			oldLocation = newLocation;
			newValue = false;
		}
		readInputs();
		appli->doStep(nStep);
		newLocation = appli->getLocation();
		if (delayMax == 0) {
			oldLocation = newLocation;
			newValue = false;
		} else {
			newValue = true;
			delay = 0;
		}
	}

void compDrone::readInputs() {
	}
void compDrone::initialize() {
		appli->initialize();
	}

void compDrone::end() {
		appli->end();
	}
	
Vector3 compDrone::getLocation() {
		return oldLocation;
	}
Drone *compDrone::getAppli() {
		return appli;
	}
	// +++++++++++++ Access for speed parameter +++++++++++++
double compDrone::getSpeed() {
		return appli->getSpeed();
	}
	
void compDrone::setSpeed(double arg) {
		appli->setSpeed(arg);
	}
	// +++++++++++++ Access for currentLocation parameter +++++++++++++
Vector3 compDrone::getCurrentLocation() {
		return appli->getCurrentLocation();
	}
	
void compDrone::setCurrentLocation(Vector3 arg) {
		appli->setCurrentLocation(arg);
	}

