/*
 * Manager.cpp
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */

#include "compManager.h"
#include "Manager.h"
compManager::compManager(double aFrequency) : LeafComponent( aFrequency) {
		appli = new Manager( this);
		delay = 0;
		delayMax = 0;
		newValue = false;
		isActive = true;
		oldNewLocation = appli->getNewLocation();
		newNewLocation = appli->getNewLocation();
	}
compManager::~compManager()	{}

void compManager::doOneStep() {
		if (newValue) {
			delay++;
			if (delay == delayMax) {
					oldNewLocation = newNewLocation;
					newValue = false;
			}
		}
	}

void compManager::doStep(int nStep) {	
		if (newValue) {
			oldNewLocation = newNewLocation;
			newValue = false;
		}
		readInputs();
		appli->doStep(nStep);
		newNewLocation = appli->getNewLocation();
		if (delayMax == 0) {
			oldNewLocation = newNewLocation;
			newValue = false;
		} else {
			newValue = true;
			delay = 0;
		}
	}

void compManager::readInputs() {
	}
void compManager::initialize() {
		appli->initialize();
	}

void compManager::end() {
		appli->end();
	}
	
Vector3 compManager::getNewLocation() {
		return oldNewLocation;
	}
Manager *compManager::getAppli() {
		return appli;
	}
	// +++++++++++++ Access for direction parameter +++++++++++++
Vector3 compManager::getDirection() {
		return appli->getDirection();
	}
	
void compManager::setDirection(Vector3 arg) {
		appli->setDirection(arg);
	}

