/* 
 * MainManager.h
 * Root Component
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */
#ifndef MainManager_H_
#define MainManager_H_

#include "compManager.h"
#include "InstDrone.h"
class InstDrone;

class MainManager : public compManager {
	protected :
              InstDrone *attInstDrone;

	public :

            MainManager(double aFrequency);
            virtual ~MainManager();

	        void setInstDrone(InstDrone *pInstDrone);

	        void readInputs()  override;
};
#endif /*  MainManager_H_ */
