/* 
 * DroneSystem.java
 * Root Component
 *
 * Generated by Cares generator, written with Acceleo
 * Author: jpb
 */

package cares.factory;

import java.util.ArrayList;
import cares.framework.LeafComponent;
import cares.framework.RootComponent;

import cares.types.Vector3;
import cares.types.WindData;
// Start of user code  : Additional imports for DroneSystem
// End of user code

public class DroneSystem extends RootComponent {

// generated pointers on child instances
	protected InstDrone instInstDrone;
	protected InstWind instInstWind;

// generated getters of child instances
public InstDrone get_InstDrone() {
		return instInstDrone;
	}
public InstWind get_InstWind() {
		return instInstWind;
	}

public DroneSystem() {
	super();
	instances = new ArrayList<LeafComponent>();
	instInstDrone = new InstDrone();
	instances.add(instInstDrone);
	instInstWind = new InstWind();
	instances.add(instInstWind);
	instInstDrone.setInstWind(instInstWind);
	instInstWind.setInstDrone(instInstDrone);
	}

public void initialize() {
	instInstDrone.setSpeed(1.);
	instInstDrone.setDirection(Vector3.FORWARD);
	instInstDrone.setDrPosition(Vector3.ZERO);
	instInstDrone.setFrequency(0.0);
	instInstWind.setWindData(new WindData(Vector3.ZERO,Vector3.ZERO));
	instInstWind.setFrequency(0.0);
	if(instInstDrone.isActive()) instInstDrone.initialize();
	if(instInstWind.isActive()) instInstWind.initialize();
// Start of user code  : Implementation of initialize method DroneSystem
// End of user code
	}

public void end() {
	instInstDrone.end();
	instInstWind.end();
// Start of user code  : Implementation of initialize method DroneSystem
// End of user code
	}
}
