/* 
 * InstWind.java
 * Root Component
 *
 * Generated by Cares generator, written with Acceleo
 * Author: jpb
 */

package cares.factory;

import cares.components.compWind;

public class InstWind extends compWind {

	protected InstDrone attInstDrone;

	public InstWind()	{
		super();
	}

	public void setInstDrone(InstDrone pInstDrone) {
		this.attInstDrone = pInstDrone;
	}

	public void readInputs() {
		appli.setPosition(attInstDrone.getPosition());
	}
}
