/* 
 * InstDrone.cpp
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */

#include "InstDrone.h"
#include "Drone.h"

InstDrone::InstDrone(double aFrequency)	: compDrone(aFrequency){
		
}
InstDrone::~InstDrone()	{
		
}
void InstDrone::setMainManager(MainManager *pMainManager) {
		attMainManager = pMainManager;
}

void InstDrone::readInputs() {
		appli->setNewLocation(attMainManager->getNewLocation());
}


