/* 
 * MainManager.cpp
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */

#include "MainManager.h"
#include "Manager.h"

MainManager::MainManager(double aFrequency)	: compManager(aFrequency){
		
}
MainManager::~MainManager()	{
		
}
void MainManager::setInstDrone(InstDrone *pInstDrone) {
		attInstDrone = pInstDrone;
}

void MainManager::readInputs() {
		appli->setDrLocation(attInstDrone->getLocation());
}


