/* 
 * DroneSystem.java
 * Root Component
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */
#ifndef DroneSystem_H_
#define DroneSystem_H_

//#include <vector>
//#include "LeafComponent.h"
#include "RootComponent.h"

#include "InstDrone.h"
#include "Vector3.h"
#include "Vector3.h"
#include "InstWind.h"
#include "WindData.h"
// Start of user code  : Additional imports for DroneSystem
// End of user code

class DroneSystem : public RootComponent {

// generated pointers on child leafComponents
	protected :
              InstDrone *instInstDrone;
              InstWind *instInstWind;


     public :
       DroneSystem();
       virtual ~DroneSystem();
// generated getters of child leafComponents
       InstDrone *get_InstDrone();
       InstWind *get_InstWind();

      void initialize() ;

      void end() ;
};
#endif /*  DroneSystem_H_ */
