/* 
 * InstDrone.h
 * Root Component
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */
#ifndef InstDrone_H_
#define InstDrone_H_

#include "compDrone.h"
#include "InstWind.h"
class InstWind;

class InstDrone : public compDrone {
	protected :
              InstWind *attInstWind;

	public :

            InstDrone(double aFrequency);
            virtual ~InstDrone();

	        void setInstWind(InstWind *pInstWind);

	        void readInputs()  override;
};
#endif /*  InstDrone_H_ */
