/* 
 * InstWind.h
 * Root Component
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */
#ifndef InstWind_H_
#define InstWind_H_

#include "compWind.h"
#include "InstDrone.h"
class InstDrone;

class InstWind : public compWind {
	protected :
              InstDrone *attInstDrone;

	public :

            InstWind(double aFrequency);
            virtual ~InstWind();

	        void setInstDrone(InstDrone *pInstDrone);

	        void readInputs()  override;
};
#endif /*  InstWind_H_ */
