/*
 * Wind.h
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */
#ifndef Wind_H_
#define Wind_H_
#include "Clock.h"
class compWind;
	// Inputs
#include "Vector3.h"
#include "Vector3.h"
#include "WindData.h"


// Start of user code  : Additional imports for Wind
// End of user code

class Wind {

	protected :
              compWind *myContainer;

	// Inputs
	          Vector3 position;
	// Outputs
	          Vector3 force;
	// Parameters
	          WindData windData;


// Start of user code  : Properties of Wind
// End of user code

	public :
            Wind(compWind *container);
            ~Wind();
	        void initialize();
	       void end();

	       void doStep(int nStep) ;
	
	
// Start of user code  : Additional methods

// End of user code
	

	     void setPosition(Vector3 arg) ;

	    Vector3 getForce();
	// +++++++++++++ Access for windData parameter +++++++++++++
	    WindData getWindData();
	
	    void setWindData(WindData arg);
};
#endif /*  Wind_H_ */
