/*
 * Drone.java
 *
 * Generated by Cares generator, written with Acceleo
 * Author: jpb
 */

package cares.components;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;

import cares.framework.LeafComponent;

import cares.application.*;

import cares.types.Vector3;



public class compDrone extends LeafComponent {

	//inputs source
	protected LeafComponent ForceSourceComponent;
	protected String portNameForce;

	protected Vector3 oldPosition;
	protected Vector3 newPosition;
	protected boolean newValue;
	protected int delay;


	protected Drone appli;

	public compDrone()	{
		appli = new Drone(this);
		delay = 0;
		delayMax = 0;
		newValue = false;
		isActive = true;
		oldPosition = appli.getPosition();
		newPosition = appli.getPosition();
	}

	public void doOneStep() {
		if (newValue) {
			delay++;
			if (delay == delayMax) {
					oldPosition = newPosition;
					newValue = false;
			}
		}
	}

	public void doStep(int nStep) {	
		if (newValue) {
			oldPosition = newPosition;
			newValue = false;
		}
		this.readInputs();
		appli.doStep(nStep);
		newPosition = appli.getPosition();
		if (delayMax == 0) {
			oldPosition = newPosition;
			newValue = false;
		} else {
			newValue = true;
			delay = 0;
		}
	}

	public void readInputs() {
	}
	
	public void initialize() {
		appli.initialize();
	}

	public void end() {
		appli.end();
	}
	
	public Vector3 getPosition() {
		return oldPosition;
	}
	public Drone getAppli() {
		return appli;
	}
	// +++++++++++++ Access for speed parameter +++++++++++++
	public Double getSpeed() {
		return appli.getSpeed();
	}
	
	public void setSpeed(Double arg) {
		appli.setSpeed(arg);
	}
	// +++++++++++++ Access for direction parameter +++++++++++++
	public Vector3 getDirection() {
		return appli.getDirection();
	}
	
	public void setDirection(Vector3 arg) {
		appli.setDirection(arg);
	}
	public void setDirection(String arg) {
		appli.setDirection(arg);
	}
	// +++++++++++++ Access for drPosition parameter +++++++++++++
	public Vector3 getDrPosition() {
		return appli.getDrPosition();
	}
	
	public void setDrPosition(Vector3 arg) {
		appli.setDrPosition(arg);
	}
}
