/*
 * WindData
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */
#include "WindData.h"
// Start of user code  : Additional imports for WindData
// End of user code

WindData::WindData() {
	}
WindData::~WindData() {
	}

WindData::WindData( Vector3 varposition, Vector3 varforce) {
		position = varposition;
		force = varforce;
	}

Vector3 WindData::getPosition () {
		return position ;
	}

void WindData::setPosition (Vector3 varposition ) {
		position  = varposition ;
	}

Vector3 WindData::getForce () {
		return force ;
	}

void WindData::setForce (Vector3 varforce ) {
		force  = varforce ;
	}

// Start of user code  : Additional methods

// End of user code


