/*
 * myDronePositionLogObservationComponent
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */
#ifndef myDronePositionLogObservationComponent_H_
#define myDronePositionLogObservationComponent_H_

#include "Clock.h"
#include "LogComponent.h"
#include <fstream>
using namespace std;
#include "Drone.h"
#include "Vector3.h"

class myDronePositionLogObservationComponent : public LogComponent {
	
	//pyp : LeafComponent qui g�n�re les donn�es sur le port (OutputPort) 
	protected :
    	Drone  *theDrone;
		//pyp : variables permettant de r�cup�rer les donn�es lues
		Vector3 instLocation;

	
	private :
		bool first = true;
	
	public :
	    myDronePositionLogObservationComponent(string filename, double aFrequency);
	    virtual ~myDronePositionLogObservationComponent();
		void readInputs();
		void WriteFirstLine();

		void setDrone(Drone *myDrone);
		void doStep(int nStep);
};
#endif /* myDronePositionLogObservationComponent */
