/* 
 * Scenario implementation
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */
#include "ScenarLog.h"
#include "Clock.h"
ScenarLog::ScenarLog(RootComponent *aRoot) : Scenario( aRoot) {
		root = aRoot;
        application = (DroneSystem *) aRoot;
	}
ScenarLog::~ScenarLog() {}	
void ScenarLog::eventSimulation() {		 
	Clock *c = Clock::getInstance();
	//long currentTime = c->getCurrentMS();
		if (c->getCurrentMS()==25000) {
			application->get_InstDrone()->setDirection( "(1,0,-1)"); 
		}
		if (c->getCurrentMS()==90000) {
			application->get_InstDrone()->setSpeed( 0.5); 
		}
}

