/*
 * compDrone.h
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */

#ifndef compDrone_H_
#define compDrone_H_

#include "LeafComponent.h"
class Drone;

#include "Vector3.h"
#include "Vector3.h"
#include "Vector3.h"
#include "Vector3.h"



class compDrone : public LeafComponent {

	protected :
/*pyp : inutile
	//inputs source
	 LeafComponent ForceSourceComponent;
	 String portNameForce;
*/
	 Vector3 oldPosition;
	 Vector3 newPosition;

	 bool newValue;
	 int delay;


	Drone *appli;

	public :
           compDrone(double aFrequency);
           virtual ~compDrone();
	       void doOneStep();
	       void doStep(int nStep);

	       virtual void readInputs() ;
	       void initialize();
	       void end();
	
	     Vector3 getPosition();
	     Drone *getAppli() ;
	// +++++++++++++ Access for speed parameter +++++++++++++
	     double getSpeed();
	
	     void setSpeed(double arg);
	// +++++++++++++ Access for direction parameter +++++++++++++
	     Vector3 getDirection();
	
	     void setDirection(Vector3 arg);
	// +++++++++++++ Access for drPosition parameter +++++++++++++
	     Vector3 getDrPosition();
	
	     void setDrPosition(Vector3 arg);
};
#endif /* compDrone_H_ */
