/*
 * compWind.h
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */

#ifndef compWind_H_
#define compWind_H_

#include "LeafComponent.h"
class Wind;

#include "Vector3.h"
#include "Vector3.h"
#include "WindData.h"



class compWind : public LeafComponent {

	protected :
/*pyp : inutile
	//inputs source
	 LeafComponent PositionSourceComponent;
	 String portNamePosition;
*/
	 Vector3 oldForce;
	 Vector3 newForce;

	 bool newValue;
	 int delay;


	Wind *appli;

	public :
           compWind(double aFrequency);
           virtual ~compWind();
	       void doOneStep();
	       void doStep(int nStep);

	       virtual void readInputs() ;
	       void initialize();
	       void end();
	
	     Vector3 getForce();
	     Wind *getAppli() ;
	// +++++++++++++ Access for windData parameter +++++++++++++
	     WindData getWindData();
	
	     void setWindData(WindData arg);
};
#endif /* compWind_H_ */
