/*
 * WindData
 *
 * Generated by Cares generator, written with Acceleo
 * Author: jpb
 */
package cares.types;

// Start of user code  : Additional imports for WindForceData
// End of user code

public class WindData {

	protected Vector3 position;
	protected Vector3 force;

	public WindData() {
	}

	public WindData( Vector3 varposition, Vector3 varforce) {
		position = varposition;
		force = varforce;
	}

	public Vector3 getPosition () {
		return position ;
	}

	public void setPosition (Vector3 varposition ) {
		this.position  = varposition ;
	}

	public Vector3 getForce () {
		return force ;
	}

	public void setForce (Vector3 varforce ) {
		this.force  = varforce ;
	}

// Start of user code  : Additional methods

// End of user code

}

