/*
 * Vector3
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */
#include "Vector3.h"
// Start of user code  : Additional imports for Vector3
// End of user code

Vector3::Vector3() {
	}
Vector3::~Vector3() {
	}

Vector3::Vector3( double varx, double vary, double varz) {
		x = varx;
		y = vary;
		z = varz;
	}

double Vector3::getX () {
		return x ;
	}

void Vector3::setX (double varx ) {
		x  = varx ;
	}

double Vector3::getY () {
		return y ;
	}

void Vector3::setY (double vary ) {
		y  = vary ;
	}

double Vector3::getZ () {
		return z ;
	}

void Vector3::setZ (double varz ) {
		z  = varz ;
	}

// Start of user code  : Additional methods

// End of user code


