/*
 * Drone.java
 *
 * Generated by Cares generator, written with Acceleo
 * Author: jpb
 */

package cares.application;

import cares.framework.Clock;
import cares.components.compDrone;
	// Inputs
import cares.types.Vector3;


// Start of user code  : Additional imports for Drone
// End of user code

public class Drone {

	protected compDrone myContainer;

	// Inputs
	protected Vector3 force;
	// Outputs
	protected Vector3 position;
	// Parameters
	protected Double speed;
	protected Vector3 direction;
	protected Vector3 drPosition;


// Start of user code  : Properties of Drone
// End of user code

	public Drone(compDrone container)	{
		myContainer = container;
// Start of user code  : Implementation of constructor method

// End of user code
	}
	public void initialize() {
// Start of user code  : Implementation of initialize method

// End of user code
	}

	public void end() {
// Start of user code  : Implementation of end method

// End of user code
	}

	public void doStep(int nStep) {
// Start of user code  : Implementation of doStep method
		long currentTime = Clock.getCurrentMS();
		// to implement
// End of user code
	}
	
	
// Start of user code  : Additional methods
	public void setDirection(String arg) {
		direction = Vector3.parse(arg);
	}
// End of user code
	

	public void setForce(Vector3 arg) {
		force = arg;
	}

	public Vector3 getPosition() {
		return position;
	}
	// +++++++++++++ Access for speed parameter +++++++++++++
	public Double getSpeed() {
		return speed;
	}
	
	public void setSpeed(Double arg) {
		speed = arg;
	}
	// +++++++++++++ Access for direction parameter +++++++++++++
	public Vector3 getDirection() {
		return direction;
	}
	
	public void setDirection(Vector3 arg) {
		direction = arg;
	}
	// +++++++++++++ Access for drPosition parameter +++++++++++++
	public Vector3 getDrPosition() {
		return drPosition;
	}
	
	public void setDrPosition(Vector3 arg) {
		drPosition = arg;
	}
}
