/*
 * Wind.java
 *
 * Generated by Cares generator, written with Acceleo
 * Author: jpb
 */

package cares.application;

import cares.framework.Clock;
import cares.components.compWind;
	// Inputs
import cares.types.Vector3;
import cares.types.WindData;


// Start of user code  : Additional imports for Wind
// End of user code

public class Wind {

	protected compWind myContainer;

	// Inputs
	protected Vector3 position;
	// Outputs
	protected Vector3 force;
	// Parameters
	protected WindData windData;


// Start of user code  : Properties of Wind
// End of user code

	public Wind(compWind container)	{
		myContainer = container;
// Start of user code  : Implementation of constructor method

// End of user code
	}
	public void initialize() {
// Start of user code  : Implementation of initialize method

// End of user code
	}

	public void end() {
// Start of user code  : Implementation of end method

// End of user code
	}

	public void doStep(int nStep) {
// Start of user code  : Implementation of doStep method
		long currentTime = Clock.getCurrentMS();
		// to implement
// End of user code
	}
	
	
// Start of user code  : Additional methods

// End of user code
	

	public void setPosition(Vector3 arg) {
		position = arg;
	}

	public Vector3 getForce() {
		return force;
	}
	// +++++++++++++ Access for windData parameter +++++++++++++
	public WindData getWindData() {
		return windData;
	}
	
	public void setWindData(WindData arg) {
		windData = arg;
	}
}
