/*
 * myDronePositionLogObservationComponent
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */
package cares.observation;
import cares.framework.LogComponent;
import cares.framework.Clock;
import cares.application.Drone;
import cares.types.Vector3;

public class myDronePositionLogObservationComponent extends LogComponent {
	
	//pyp : LeafComponent qui g�n�re les donn�es sur le port (OutputPort) 
    protected Drone myDrone = null;
	//pyp : variables permettant de r�cup�rer les donn�es lues
	protected Vector3 instPosition = null;

	
	private boolean first = true;
	
	public void readInputs() {
    instPosition = myDrone.getPosition();
	}
	//fin 
	
	public  myDronePositionLogObservationComponent(String filename, double aFrequency) {
		super(filename, aFrequency);
 		try{
            WriteFirstLine();
		}
		catch (Exception e) {e.printStackTrace();}
		
	}
	@Override	
	public void WriteFirstLine() throws Exception {
    String s = "time(ms)";
        s = s + ";" + "X.x;Y.y;Z.z";
		writeNames( s);
		endLine();
	}

	public void setDrone(Drone myDrone) {
		this.myDrone = myDrone;
	}

	@Override
	public void doStep(int nStep) {
		this.readInputs();
		int i = 0;
        long t = Clock.getCurrentMS();
        String s = Long.toString( t) + ";";
		try{

			s = s + instPosition.getX() + ";";

			s = s + instPosition.getY() + ";";

			s = s + instPosition.getZ() + ";";		}
		catch (Exception e) {
			s = s + "error";}

		//on retire le dernier ";" separateur
		//s = s.substring(0, s.length() - 1);
		writeNames( s);
		endLine();
    }
    }
