/* 
 * InstDrone.cpp
 *
 * Generated by Cares generator, written with Acceleo
 * Author: pyp
 */

#include "InstDrone.h"
#include "Drone.h"

InstDrone::InstDrone(double aFrequency)	: compDrone(aFrequency){
		
}
InstDrone::~InstDrone()	{
		
}
void InstDrone::setInstWind(InstWind *pInstWind) {
		attInstWind = pInstWind;
}

void InstDrone::readInputs() {
		appli->setForce(attInstWind->getForce());
}


